# dataset config : Sequential Recommendation
data_path: ./data/processed

format: sequential
target: True
behavior: True
item_augmented: False
seq_augmented: False

#tokenizer
tokenizer_type: Chunked
K: 64
item_len: 3
max_seq_len: 202  # [BOS/USER_TOKENS, BEHAVIOR_TOKENS, ITEM_TOKENS_1, ITEM_TOKENS_2, ITEM_TOKENS_3 ... ] 50 interactions * 4
min_seq_len: 1
behavior_tokens: [1,2]
id_offsets: [0, 3, 19, 35, 51] # token offset for each layer of semantic token, 1-2(behaviors), 3-18, 19-34, 35-50. Use smaller gap for our creatives
BOS_token: 0 # BOS must be set to 0, EOS is automatically set to be the last token after BOS, special, and item tokens
num_user_tokens: 2000
random_map: True
# TIGER:

# T5:
T5_type: "PBA"
behavior_injection: True
behavior_embedding_dim: 64
num_positions: 4
num_behavior: 2
num_layers: 2 # initial was 4
num_decoder_layers: 2 # initial was 4
num_sparse_encoder_layers: 2
num_sparse_decoder_layers: 2
sparse_layers_encoder: []
sparse_layers_decoder: [0, 1, 2, 3]
behavior_injection_encoder: [0, 1]
behavior_injection_decoder: [0, 1]
d_model: 64 # initial was 256
d_ff: 128 # initial was 512
num_heads: 4 # initial was 6
d_kv: 64
dropout_rate: 0.0
activation_function: "relu"
feed_forward_proj: "relu"
n_positions: 50

#trainer:
exp_id: "CID_1800flowers"
steps: 70000 # Initial was 350000
lr: 0.001
warmup_steps: 3000
weight_decay: 0.005
batch_size: 1024 # Initial was 512
eval_batch_size: 32 # Initial was 32
patience: 10
auto_save_epochs: 5
epochs_per_eval: 3 # Initial was 1
epochs_per_all_eval: 3 # Initial was 1
decoder_input: [0,1] # 0: BOS, 1: target behavior token
sample_ratio: 1.0